# Generated by Django 5.1.5 on 2025-02-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='department',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='city',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_expired_date',
            new_name='job_expiry',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='address',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='max_salary',
            new_name='salary_max',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='min_salary',
            new_name='salary_min',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='required_skills',
            new_name='skills_required',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.AlterField(
            model_name='job',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_level',
            field=models.CharField(choices=[('entry', 'Entry'), ('mid', 'Mid'), ('senior', 'Senior')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('remote', 'Remote')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
