# Generated by Django 5.1.7 on 2025-04-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0004_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(choices=[('it', 'Information Technology'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('engineering', 'Engineering'), ('design', 'Design'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 Years'), ('1-3', '1-3 Years'), ('3-5', '3-5 Years'), ('5-7', '5-7 Years'), ('7-10', '7-10 Years'), ('10+', '10+ Years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualification',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('certification', 'Professional Certification'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=200),
        ),
    ]
