# Generated by Django 5.1.7 on 2025-03-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_update_leavetype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ['name']},
        ),
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_leavetype' AND column_name = 'leave_type') THEN
                    ALTER TABLE hrm_leavetype DROP COLUMN leave_type;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_leavetype' AND column_name = 'number_of_days') THEN
                    ALTER TABLE hrm_leavetype DROP COLUMN number_of_days;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_leavetype' AND column_name = 'policy_name') THEN
                    ALTER TABLE hrm_leavetype DROP COLUMN policy_name;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE hrm_leavetype 
            ADD COLUMN IF NOT EXISTS leave_type varchar(100),
            ADD COLUMN IF NOT EXISTS number_of_days integer,
            ADD COLUMN IF NOT EXISTS policy_name varchar(100);
            """
        ),
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name = 'hrm_leavetype' AND column_name = 'created_at') THEN
                    ALTER TABLE hrm_leavetype ADD COLUMN created_at timestamp with time zone NULL;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name = 'hrm_leavetype' AND column_name = 'default_days') THEN
                    ALTER TABLE hrm_leavetype ADD COLUMN default_days integer DEFAULT 0;
                END IF;
                
                IF NOT EXISTS (SELECT 1 FROM information_schema.columns 
                             WHERE table_name = 'hrm_leavetype' AND column_name = 'updated_at') THEN
                    ALTER TABLE hrm_leavetype ADD COLUMN updated_at timestamp with time zone NULL;
                END IF;
            END $$;
            """,
            reverse_sql="""
            ALTER TABLE hrm_leavetype 
            DROP COLUMN IF EXISTS created_at,
            DROP COLUMN IF EXISTS default_days,
            DROP COLUMN IF EXISTS updated_at;
            """
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Permission', 'Permission'), ('Uninformed', 'Uninformed')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
