# Generated by Django 5.1.7 on 2025-03-31 10:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_alter_leavetype_options_remove_leavetype_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(),
        ),
    ]
