# Generated by Django 5.1.7 on 2025-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0005_attendance_date_alter_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
    ]
