# Generated by Django 5.1.7 on 2025-03-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_remove_attendance_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_attendance' AND column_name = 'check_in') THEN
                    ALTER TABLE hrm_attendance ALTER COLUMN check_in TYPE time without time zone;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_attendance' AND column_name = 'check_out') THEN
                    ALTER TABLE hrm_attendance ALTER COLUMN check_out TYPE time without time zone;
                END IF;
            END $$;
            """,
            reverse_sql="""
            DO $$ 
            BEGIN
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_attendance' AND column_name = 'check_in') THEN
                    ALTER TABLE hrm_attendance ALTER COLUMN check_in TYPE time without time zone;
                END IF;
                
                IF EXISTS (SELECT 1 FROM information_schema.columns 
                          WHERE table_name = 'hrm_attendance' AND column_name = 'check_out') THEN
                    ALTER TABLE hrm_attendance ALTER COLUMN check_out TYPE time without time zone;
                END IF;
            END $$;
            """
        ),
    ]
