# Generated by Django 5.1.7 on 2025-03-31 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0008_alter_attendance_options_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
