# Generated by Django 5.1.7 on 2025-03-31 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0010_add_timesheet_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_time', models.IntegerField(help_text='Break time in minutes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='timesheet',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='number_of_days',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='policy_name',
        ),
        migrations.RemoveField(
            model_name='timesheet',
            name='remaining_hours',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='default_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee'),
        ),
        migrations.CreateModel(
            name='OldAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('break_time', models.CharField(blank=True, max_length=20, null=True)),
                ('late_minutes', models.IntegerField(default=0)),
                ('production_hours', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('permission', 'Permission'), ('uninformed', 'Uninformed')], default='present', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
        ),
    ]
